### PR TITLE
AutoService is not necessarily should leave traces in class files!

### PR DESCRIPTION
**Pull request by SaltOfTheFlame**

### CODE REVIEW

**Comment by JakeWharton** [comment]
:+1: This was fixed for other autos. Guess this guy was missed.

**Comment by cgruber** [comment]
Can you please update the CLA per the instructions?

**Comment by SaltOfTheFlame** [comment]
what shoulld I do with that thing? I've already agreed to CLA

**Comment by ronshapiro** [comment]
In the meantime, we had done something similar. I'll close this.

**Pull request closed without merging**
