### PR TITLE
We now require Java 8, so remove the @Ignore on annotationReferencesUndefinedTest

### PR DESCRIPTION
**Pull request by eamonnmcmanus**
-------------
Created by MOE: https://github.com/google/moe
MOE_MIGRATED_REVID=151405078

### CODE REVIEW

**Comment by ronshapiro** [comment]
LGTM (assuming you figure out that failure)

**Comment by eamonnmcmanus** [comment]
The failure is very strange. It's in a test that this PR doesn't touch, so I think it would probably have happened without the PR? I'm trying to see if I can reproduce it.

**Comment by eamonnmcmanus** [comment]
I don't know what's up here and I can't reproduce it, even by making a very similar PR. So I'm going to merge this anyway and see what happens.

**Comment by eamonnmcmanus** [comment]
Travis is passing now. We have some sort of transient problem, which *might* be fixed by adding `-implicit:none` to the various compilations in `CompilationTest.java`. If it starts occurring more reproducibly I will investigate further.

**Pull request merged**
