### PR TITLE
Adding @Generated annotation only when it's present on the classpath

### PR DESCRIPTION
**Pull request by blipinsk**
The new `MemoizeExtension` wasn't taking into account the possibility that `@Generated` annotation isn't present on classpath (see Issue #398).

This pull request fixes the problem (using the same convention that was previously used for `com.google.errorprone.annotations.concurrent.LazyInit`).

### CODE REVIEW

**Comment by blipinsk** [comment]
I signed it!

**Comment by blipinsk** [comment]
Not sure why travis fails... Those tests pass for me locally. More so the `ExtensionTest` fails, which shouldn't be affected by my changes to MemoizeExtension.java.

**Comment by eamonnmcmanus** [comment]
Looks like we fixed this independently in AutoValue 1.5.1. :-/

**Comment by blipinsk** [comment]
Glad it was fixed 😋

**Pull request closed without merging**
