### PR TITLE
Add Diffblue Deeptest Tests

### PR DESCRIPTION
**Pull request by AbbasKhan1110**
The test cases contained in this PR were automatically generated by [Diffblue's](http://www.diffblue.com) [Deeptest](http://www.diffblue.com/papers/overview.pdf) software. Please feel free to merge them into your repository.

These tests are part of a batch of 227 in total, providing an increase of 22.64% in line coverage.

We would be happy to provide further tests via a subsequent PR.

Results for various open source projects can be viewed at:
http://diff.blue/demo

We welcome any feedback you have on these tests.

### CODE REVIEW

**Comment by eamonnmcmanus** [comment]
It looks as if this PR introduces test errors on JDK 9 that were not there before.

**Comment by AbbasKhan1110** [comment]
Hi, we have noticed this issue & are looking for a solution internally. We will update this PR whenever there are new developments.

**Comment by AbbasKhan1110** [comment]
@googlebot I signed it!

**Comment by eamonnmcmanus** [comment]
The checks are still failing. But anyway, before you spend too much time addressing that, perhaps you can say a bit more about what the advantage of merging this PR would be for us? Does it commit us to using Deeptest in the future? The tests here don't look as if they're intended to be modified by humans. What would our development flow be if we accepted them?

**Comment by paulkennethkent** [comment]
Thanks for your feedback on our tests. The purpose of this PR is to allow you a chance to review a smaller set of tests created for this project ahead of a potential subsequent PR for the complete group of tests produced (227 in this case)

The benefits for you are the increase in line coverage (22.64%) from the complete set of tests, which do not need to be created manually, thus saving valuable time for developers.

We do not expect any commitment to use Deeptest in the future - one of our missions is to provide useful tests to open source projects.

The tests represent a snapshot of a project's source code as it is, so they are all expected to run successfully until a time when the software in question changes, either by design or the introduction of a bug. At that time, a choice can be made to modify a test manually or remove it, if it is no longer relevant.

We do expect our tests to be manually modified but recognise that they have scope for improvement in terms of human readability - something we are constantly striving for. To this end we appreciate any feedback we receive from project owners and are keen to act on any identified areas for improvement.

**Comment by cpovirk** [comment]
Mass-closing PRs without an accepted [CLA](https://cla.developers.google.com/about). You're welcome to reopen if you get the check to pass. Alternatively, feel free to open a plain issue to describe the change you'd like to see made.

**Pull request closed without merging**
