### PR TITLE
Merge MOE writing branch form f10d5c96e7270eeccbdef00bda965da8ae865c26

### PR DESCRIPTION
**Pull request by cgruber**
Includes:

  * Some javadoc and readme fixes
  * Improve handling of "collection builders" in AutoValue
  * Improve generics handling in some inheritance cases in AutoValue
  * Crisper handling of equivalences in MoreTypes in Common
  * Fix the shading to be more reasonably named in AutoValue
  * Better generics handling in eclipse in AutoValue
  * AnnotationValues is now available in auto-common
  * Improve error handling in AuotValue
  * Push our internal AutoValue user guide out (though not into a gh-pages site, just as .md files in the source tree)
  * Minor maintenance work

### CODE REVIEW

**Comment by cgruber** [comment]
@rharter - can you please verify that you are ok with your authorship being represented in this code-line?  For some reason our CLAbot can't assert that you have consented to have your contributions included. :/

**Comment by eamonnmcmanus** [comment]
Are we missing a test dependency on Guava? I'm talking about the MoreObjects error failure from Travis.

**Comment by cgruber** [comment]
Ugh.  Yes.  Unfortunately, we aren't missing a test dependency on Guava, we're relying on Guava 18.0, so I have no idea how this passed the maven build internally.  So frustrating.  I'll circle back on this, figure out what went wrong, and update this pull tomorrow.

**Comment by cgruber** [comment]
Ok - that should do it.

**Comment by cgruber** [comment]
@eamonnmcmanus - can you PTAL?

**Comment by eamonnmcmanus** [comment]
LGTM

**Pull request merged**
