### PR TITLE
Update the Gradle instructions

### PR DESCRIPTION
**Pull request by vogella**
The previous instruction compileOnly and apt did not work for me in an new Android project created with latest Android Studio Beta.

### CODE REVIEW

**Comment by jbduncan** [comment]
Do these new instructions work with bog standard Java builds?

**Comment by jbduncan** [comment]
And for Android, is @tbroyer's apt plugin mentioned above in the source even needed?

**Comment by devisnik** [comment]
@vogella The original instructions refer to integration into a regular Gradle java project. You might want to add android-specific ones instead of overriding them.

**Comment by vogella** [comment]
Thanks for the feedback, I think it is better to close this request for now.

**Pull request closed without merging**
