### PR TITLE
Release AutoValueBuilderProcessor to open-source.

### PR DESCRIPTION
**Pull request by cgruber**
Release AutoValueBuilderProcessor to open-source.
-------------
Created by MOE: http://code.google.com/p/moe-java
MOE_MIGRATED_REVID=84473406

### CODE REVIEW

**Comment by cgruber** [comment]
Overriding CLAbot, since eamonn is a googler.

**Comment by cgruber** [comment]
PTAL @eamonnmcmanus

**Comment by cgruber** [comment]
Hey @eamonnmcmanus - it seems a few auto-value tests are failing in open-source.  Can you peek at the travis build here, and see what's up?  I'm going to manually issue a "common" snapshot so I can proceed with the dagger export.

**Comment by eamonnmcmanus** [comment]
I'm going to merge this PR and investigate the failure. It is in some recently changed code, but it's not clear to me why it should fail.

**Comment by eamonnmcmanus** [comment]
I think the failure is due to version skew between AutoValue and AutoCommon. There's a change to AutoCommon that causes it to take the name of a TypeVariable into account when comparing for equality. This change isn't in AutoCommon 0.3, which is what the POM for AutoValue is specifying as a dependency. The failing test is assuming that that change is present. It should pass if you make an AutoCommon 0.4 and have AutoValue depend on that.

**Pull request merged**
