### PR TITLE
Update stale references from Java 1.6 to 1.7

### PR DESCRIPTION
**Pull request by gaul**
References #449.

### CODE REVIEW

**Comment by andrewgaul** [comment]
It would also be nice to document this new requirement in the release notes:

https://github.com/google/auto/releases/tag/auto-value-1.5

**Comment by eamonnmcmanus** [comment]
The suggestion about the release notes is good and I have followed it.

There's a certain ambiguity about what we mean when we say that this is "for" a certain version of Java. It is true that the compiler must now be at least a Java 8 compiler. However it can still be used to generate Java 7 code, and I expect people to continue doing that for quite some time on Android. I think it might be best to delete these places where we say "for" some version, and instead add a note about versions to the user guide. I think it is reasonable to assume that nearly all users are on Java 8 tooling at this point, and those who are not should already be used to not everything being available to them.

Did you run into the Java 8 requirement yourself? What was the context?

**Comment by JakeWharton** [comment]
The class files in 1.5 use version 52 (Java 8) which means a JDK 7 compiler
won't be able to use the annotation I believe.

**Comment by rharter** [comment]
Correct, you'll get this if you try: https://github.com/rharter/auto-value-gson/issues/142

**Comment by eamonnmcmanus** [comment]
@JakeWharton I didn't think I said anything different.

**Comment by JakeWharton** [comment]
The change in retention means much more of your toolchain is impacted. Retaining the auto value class files on a classpath to appease tools looking at such things and the lack of split between annotation and compiler means the Java 7 thing is only _mostly_ accurate.

**Comment by JakeWharton** [comment]
Starting with version 3.0 of the Android plugin we actually have a nice get-out-of-jail-free card where the whole toolchain now supports Java 8 class files to make this a non-problem. But it's currently opt-in ☹️

**Comment by eamonnmcmanus** [comment]
Interesting. The case for separate artifacts is certainly stronger now, since that would make it easier for AutoValue.class to be a Java 7 class file.

**Comment by andrewgaul** [comment]
Thanks for updating the release notes -- this reflects my experience testing locally.  I updated the pull request to Java 1.7 but please close it if you plan a larger explanation based on this discussion.  For what it is worth, I am testing with Apache jclouds which still supports Java 1.6.

**Pull request closed without merging**
