### PR TITLE
AutoService: Add support for multiple service in one service provider

### PR DESCRIPTION
**Pull request by TomLottermann**
In my project I have many very small services which I Implemented in one class. This is paticularly useful if these services share a common interface.

Sadly however I found out that AutoService does not support that case.

In this commit I added the possiblity to specify multiple services in a single `@AutoService` annotation.

### CODE REVIEW

**Comment by LookaPW** [comment]
Will this ever be merged? I am looking forward to this pull request.

**Comment by willdurand** [comment]
This improvement would be awesome! 👍

**Comment by henryptung** [comment]
Also looking forward to this.

**Comment by eamonnmcmanus** [comment]
This functionality was implemented by #548.

**Pull request closed without merging**
