### PR TITLE
Pull request for Issue #81Provide OSGi meta data

### PR DESCRIPTION
**Pull request by sarod**
Pull request for Issue #81.

Provide OSGI manifest attributes for auto-value, auto-factory and auto-service using maven-bundle-plugin.

Note that auto-factory does not compile currently. It complains about missing dagger  2.0-SNAPSHOT dependency I tried using the 2.0 but it then fails with compile errors. So I was not able to test the proposed changes are not tested for auto-factory.

### CODE REVIEW

**Comment by sarod** [comment]
Travis Build fails because dagger 2.0-SNAPSHOT is missing. 
(Pull Request #228 is supposed to fix this)

**Comment by cgruber** [comment]
AutoFactory has now removed dependency on dagger, so the build should work just fine.

**Comment by sarod** [comment]
Is there any chance of this being merged before release of auto-value 1.1?

**Comment by sarod** [comment]
This pull request is probably outdated by now. 
@cgruber I didn't get any feedback on the original pull request should I rebase it ? Are you accepting contributions on this issue?

**Comment by eamonnmcmanus** [comment]
What do you see as the principal benefits of this change?

**Comment by sarod** [comment]
@eamonnmcmanus sorry for the late replay I missed your answer.

OSGI manifest attributes contain runtime metadata. So given the fact that there is no reference to auto-value at runtime it could seem useless to include OSGI metadata.

However some OSGI development environment like eclipse (PDE) uses the OSGI metadata to build the classpath used for compilation. 
So the lack of OSGI metadata on autovalue makes auto-value unusable in PDE.

**Pull request closed without merging**
