### PR TITLE
Separate auto-factory compiler and annotations.

### PR DESCRIPTION
**Pull request by CoatedMoose**
No code changes, just moving files and pom configuration changes.

See issue google/auto#268.

### CODE REVIEW

**Comment by CoatedMoose** [comment]
I signed it!

**Comment by CoatedMoose** [comment]
I expect my pom changes might need some tweaks to conform with project conventions. I am happy to do the other projects, but I don't want to change everything and find out a different approach for separating the projects is preferred.

**Comment by cypressious** [comment]
Any updates on this since 2016?

**Comment by cpovirk** [comment]
From https://github.com/google/auto/issues/268, it sounds like the split happened.

**Comment by shalk** [comment]
i think the split is not happened for  auto-factory compiler and annotations.

**Comment by cpovirk** [comment]
Thanks, my mistake.

Hmm, I can't seem to reopen this for some reason....

**Comment by cpovirk** [comment]
Wait, now it is letting me?

**Comment by cpovirk** [comment]
The UI is confusing me. First, it had "Reopen and comment" grayed out. Then, after I posted, it became available, so I posted again, and I'm pretty sure that I pressed it, but it didn't reopen. That probably does mean that the branch (or entire fork) was deleted after my wrongly closing the PR years ago. Opening another issue sounds wise. Sorry for the trouble.

**Comment by cpovirk** [comment]
Yeah, now the button is available again, but I assume it's still not going to work?

**Comment by cpovirk** [comment]
Yeah, it let me click it, but when I hovered before doing so, it told me that the repo that contained the PR had been deleted.

**Comment by CoatedMoose** [comment]
It's been a hot minute since this was initially opened, and subsequently closed. I presumably deleted my fork when this issue was closed.

I've recreated my changes on the latest HEAD. See if you can reopen the PR now. If not, I'll open a new PR.

**Comment by cpovirk** [comment]
It doesn't seem like it's about to let me, but let me confirm that I see the same thing as before after I post this comment.

**Comment by cpovirk** [comment]
Yep, same message when I hover as before. I'll press "Reopen and comment" again for fun, but unless you see this actually reopen at that point, then a new PR is the way to go.

It seems entirely likely that we will continue to drag on doing anything about it—I wonder if we were concerned that users would need to update their build configuration when they upgrade?—but it's a highly legitimate request, and it would obviously be the right approach if we were starting from scratch.

**Comment by CoatedMoose** [comment]
Opened a new PR in #1814. I'll continue discussion over there.

**Pull request closed without merging**
