### PR TITLE
Removes toBuilder method from Extension Context properties method

### PR DESCRIPTION
**Pull request by lucastsa**
Current implementation returns `toBuilder` as a property in the `AutoValueExtension.Context` `properties()` passed to extensions, which causes problems when using extensions on classes that use Builders.

This pull requests removes the toBuilder method from the properties in the same fashion that was already being done in the `defineVarsForType` method.

### CODE REVIEW

**Comment by eamonnmcmanus** [comment]
Thanks for this contribution! However, I have a restructuring of the Extensions support that is close to completion and it will solve this problem among others.

**Comment by lucastsa** [comment]
Thanks for letting me know, @eamonnmcmanus. Does the restructuring include information about the class builder to the extension?

**Comment by eamonnmcmanus** [comment]
Not currently. Do you have a particular need that might be addressed by that?

**Comment by lucastsa** [comment]
Possibly. I've seen the exchanges in #278 and realized that it is unlikely that a solution where `setX(T)` is going to be implemented, as the consensus seems to be that setX(null) should not mean `Optional.empty()` / `Optional.absent()`. An alternative solution to who uses that pattern `Optional<T> getX()` + `Builder.setX(T)`, where the non-serializable `java.util.Optional` is only used as a return type, could be provided by an extension, that would require implementing a setter in a builder subclass and possibly "consume" those properties so that AutoValue doesn't complain about property type mismatch.

**Comment by eamonnmcmanus** [comment]
I haven't given the matter much thought, but since the generated Builder is nested inside the generated AutoValue_Foo, and extensions work by subclassing the former, they could potentially subclass the latter too. Currently the generated Builder class is final but we could turn that off when extensions are present. I think we'd need to have some clear use cases first. I'm not sure that "knowing whether properties have been set" is a good enough one, because I think the planned `Optional<T>` solution for it is going to be enough for most users.

**Pull request closed without merging**
