### PR TITLE
Add support for Nullable on Optional property builders

### PR DESCRIPTION
**Pull request by kenzierocks**
This allows an `@Nullable` annotation to exist on a `Builder` property setter for an `Optional` property, like so: `Builder bar(@Nullable String bar);`. It uses `ofNullable`/`fromNullable` to convert the value to the correct `Optional` instance. ~~This PR also replaces the logic in the `Builder` property getters to use `ofNullable`/`fromNullable` instead of an `if ($p == null)` check.~~ (Edit: This doesn't work with `Optional` primitives + wrapper classes.)

This solves my request here: https://github.com/google/auto/issues/278#issuecomment-226660312, and #384.

### CODE REVIEW

**Comment by Enfernuz** [comment]
Any plans on merging this in the near future?

**Comment by eamonnmcmanus** [comment]
I'm reworking other aspects of builders at the moment but I will look into this when I am done.

**Comment by kenzierocks** [comment]
I've just rebased onto the latest `master`, to resolve merge conflicts.

**Comment by kenzierocks** [comment]
It's been updated again to handle the latest changes.

**Comment by eamonnmcmanus** [comment]
It looks as if there's still a test failure.

I'm hoping to cut AutoValue 1.4 soon, but I will look at this and https://github.com/google/auto/pull/444 once that is done. Thanks for putting in the work to put them together!

**Comment by eamonnmcmanus** [comment]
Meanwhile, can I ask that you add test code to [AutoValueTest](https://github.com/google/auto/blob/master/value/src/it/functional/src/test/java/com/google/auto/value/AutoValueTest.java) in this PR and the other one?

**Comment by kenzierocks** [comment]
Let me know if you would like any other test cases for this PR.

**Comment by PierreMage** [comment]
Is it planned to merge this PR in the near future?

**Comment by gmalmquist** [comment]
Any activity happening on this? Has this been superseded by something else?

**Comment by smac89** [comment]
I'm surprised this hasn't been merged yet. What is the delay (apart from the conflicts which keep getting fixed)?

**Comment by eonwhite** [comment]
I'd also love to see this feature get merged. It's really my only complaint with AutoValue -- right now the workaround (creating two versions of every builder method where you want to allow passing null) is very tedious.

**Comment by kenzierocks** [comment]
I've just fixed up this PR to match `master`. I do have concerns over not having the static method `AutoValueProcessor.nullableAnnotationIfInList`, but I don't see a better place for it.

**Comment by eamonnmcmanus** [comment]
Sorry to have dropped the ball on this. I've put together a modified version of this change and am sending it out for internal review. Thanks, @kenzierocks!

**Pull request closed without merging**
