### PR TITLE
Fix readme file formatting

### PR DESCRIPTION
**Pull request by ming13**

### CODE REVIEW

**Comment by eamonnmcmanus** [comment]
Are the changes here just to unindent the code samples? What is the motivation?

**Comment by ming13** [comment]
Yep, it just removes an extra top-level indentation—compare [this](https://github.com/ming13/auto/blob/readme-forma/value/README.md#builders) and [this](https://github.com/google/auto/tree/master/value#builders). In [such places](https://github.com/ming13/auto/blob/readme-forma/value/README.md#in-pomxml) it can help with a copy-paste procedure.

**Comment by eamonnmcmanus** [comment]
Actually the current indentation does seem a bit gratuitous. @kevinb9n is there a reason for it?

**Comment by kevinb9n** [comment]
It probably just came over in the conversion from Docs. I agree it's
unnecessary.

On Sun, Sep 13, 2015 at 12:09 PM, Éamonn McManus <notifications@github.com>
wrote:

> Actually the current indentation does seem a bit gratuitous. @kevinb9n
> <https://github.com/kevinb9n> is there a reason for it?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/google/auto/pull/266#issuecomment-139908788>.
>



-- 
Kevin Bourrillion | Java Librarian | Google, Inc. | kevinb@google.com

**Comment by eamonnmcmanus** [comment]
OK. We'll merge this change in by syncing it into Google's code base. It'll show up when we sync back out.

**Comment by eamonnmcmanus** [comment]
Committed as 4a65dd332091df2512bcc24fffd5a4fdcc64119c.

**Pull request closed without merging**
