### PR TITLE
Prefer javax.annotation.processing.Generated on Java 9

### LINKED ISSUE #560: NoClassDefFoundError: javax/annotation/Generated on Java 9
//CC @cushon 

This is the very first time, I'm trying to build [Gerrit Code Review](https://gerrit.googlesource.com/gerrit) with Bazel, with Java 9. We have this Bazel patch: https://github.com/hhclam/bazel/commit/64212c8026df9fc6361d5af8414acc373e221955.

One issue is EP doesn't really work with mentioned Bazel patch, the vanilla javac is used and not the bundled one with Bazel:

```
ERROR: /home/davido/projects/gerrit2/java/com/google/gerrit/common/BUILD:32:1: Building java/com/google/gerrit/common/libserver.jar (57 source files) failed (Exit 1)
java/com/google/gerrit/common/RawInputUtil.java:34: error: [CheckReturnValue] Ignored return value of method that is annotated with @CheckReturnValue
    Preconditions.checkNotNull(bytes);
                              ^
    (see http://errorprone.info/bugpattern/CheckReturnValue)
  Did you mean to remove this line?
[...]
ERROR: /home/davido/projects/gerrit2/java/com/google/gerrit/util/cli/BUILD:1:1: Building java/com/google/gerrit/util/cli/libcli.jar (6 source files) failed (Exit 1)
java/com/google/gerrit/util/cli/CmdLineParser.java:229: error: [CheckReturnValue] Ignored return value of method that is annotated with @CheckReturnValue
        map.put(ent.getKey(), val);
               ^
    (see http://errorprone.info/bugpattern/CheckReturnValue)
  Did you mean to remove this line?
Target //java/com/google/gerrit/server:server failed to build
```

EP can be disabled for now, using: --javacopt="-XepDisableAllChecks" option.

Gerrit issue, is outdated auto-value version used (1.4.1). That's because the `auto-value` upgrade had to be reverted due to Eclipse-Oxygen bug, that was fixed meantime, but wasn't released yet. 

Auto-value is upgraded with this diff (applied on gerrit master):

```
diff --git a/WORKSPACE b/WORKSPACE
index 6810f79c93..4f5de9b620 100644
--- a/WORKSPACE
+++ b/WORKSPACE
@@ -408,8 +408,8 @@ maven_jar(
 
 maven_jar(
     name = "auto_value",
-    artifact = "com.google.auto.value:auto-value:1.4.1",
-    sha1 = "8172ebbd7970188aff304c8a420b9f17168f6f48",
+    artifact = "com.google.auto.value:auto-value:1.5.2",
+    sha1 = "1b94ab7ec707e2220a0d1a7517488d1843236345",
 )
 
 maven_jar(
```

With these three fixes:

- Custom Bazel build
- Disabled EP
- Auto-Value upgrade to 1.5.2

trying to build `java/com/google/gerrit/sshd:sshd` on Java 9 is failing with:

```
$ /home/davido/projects/bazel/bazel-bin/src/bazel build java/com/google/gerrit/sshd:sshd --javacopt="-XepDisableAllChecks" --host_java_toolchain=@bazel_tools//tools/jdk:jdk9 --java_toolchain=@bazel_tools//tools/jdk:jdk9
INFO: Analysed target //java/com/google/gerrit/sshd:sshd (0 packages loaded).
INFO: Found 1 target...
ERROR: /home/davido/projects/gerrit/java/com/google/gerrit/sshd/BUILD:1:1: Building java/com/google/gerrit/sshd/libsshd.jar (97 source files) and running annotation processors (AutoAnnotationProcessor, AutoValueProcessor) failed (Exit 1)
java.lang.RuntimeException: java.lang.NoClassDefFoundError: javax/annotation/Generated
	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.handleExceptions(JavacTaskImpl.java:158)
	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:96)
	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:90)
	at com.google.devtools.build.buildjar.javac.BlazeJavacMain.compile(BlazeJavacMain.java:107)
	at com.google.devtools.build.buildjar.SimpleJavaLibraryBuilder$1.invokeJavac(SimpleJavaLibraryBuilder.java:105)
	at com.google.devtools.build.buildjar.ReducedClasspathJavaLibraryBuilder.compileSources(ReducedClasspathJavaLibraryBuilder.java:54)
	at com.google.devtools.build.buildjar.SimpleJavaLibraryBuilder.compileJavaLibrary(SimpleJavaLibraryBuilder.java:108)
	at com.google.devtools.build.buildjar.SimpleJavaLibraryBuilder.run(SimpleJavaLibraryBuilder.java:116)
	at com.google.devtools.build.buildjar.BazelJavaBuilder.processRequest(BazelJavaBuilder.java:105)
	at com.google.devtools.build.buildjar.BazelJavaBuilder.runPersistentWorker(BazelJavaBuilder.java:67)
	at com.google.devtools.build.buildjar.BazelJavaBuilder.main(BazelJavaBuilder.java:45)
Caused by: java.lang.NoClassDefFoundError: javax/annotation/Generated
	at com.google.auto.value.processor.AutoAnnotationProcessor.getReferencedTypes(AutoAnnotationProcessor.java:450)
	at com.google.auto.value.processor.AutoAnnotationProcessor.processMethod(AutoAnnotationProcessor.java:152)
	at com.google.auto.value.processor.AutoAnnotationProcessor.process(AutoAnnotationProcessor.java:129)
	at com.google.auto.value.processor.AutoAnnotationProcessor.process(AutoAnnotationProcessor.java:113)
	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:968)
	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:884)
	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.access$2200(JavacProcessingEnvironment.java:108)
	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1206)
	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1315)
	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1246)
	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:922)
	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.lambda$doCall$0(JavacTaskImpl.java:100)
	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.handleExceptions(JavacTaskImpl.java:142)
	... 10 more
Caused by: java.lang.ClassNotFoundException: javax.annotation.Generated
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:466)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:563)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
	... 23 more
Target //java/com/google/gerrit/sshd:sshd failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.626s, Critical Path: 0.43s
FAILED: Build did NOT complete successfully
```

Environment: Linux.

```
$ java -version
openjdk version "9.0.1"
```

### PR DESCRIPTION
**Pull request by davido**
Closes #560.

### CODE REVIEW

**Comment by davido** [comment]
CI failure seems to be related:

```
/home/travis/build/google/auto/value/src/main/java/com/google/auto/value/processor/AutoAnnotationProcessor.java:[20,30] cannot find symbol

  symbol:   class GeneratedAnnotations

  location: package com.google.auto.common

[INFO] 1 error
```

But, I havn't added this class in `auto/common` in this change, it was already added before. Not sure, what is the right order of actions here, for this method to be available in `auto/value`.

For my tests, I installed auto/common locally and bumped the version used in auto/value. I was able to build gerrit with this patch on Java 9 without any issue.

**Comment by tbroyer** [comment]
`value/pom.xml` needs to bump auto-common to 0.9.

**Comment by davido** [comment]
> value/pom.xml needs to bump auto-common to 0.9.

Thanks! Done.

**Comment by davido** [comment]
Seems to be fixed with f04406c1f11d3796bd93ed89ae160f47bcb4b7e4.

**Pull request closed without merging**
